packages:
  - dialog
  - gateway
  - playground
  - runtime
  - shell-commands
  - sig-verify
  - styles
  - ui
catalog:
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0
  '@zod/mini': ^4.0.0-beta.20250505T195954
  '@types/node': ^22.15.3
  react-dom: ^19.1.0
  react: ^19.1.0
  typescript: 5.8.3
