"$schema" = "node_modules/wrangler/config-schema.json"

name = "mcp-magnet-gateway"
compatibility_date = "2025-06-13"

routes = [
  { pattern = "open.mcpmagnet.app", custom_domain = true }
]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
